### ISSUE TITLE
Smart Action on inline tags broken

### ISSUE THREAD

**Issue by srackham** [obsidian-nvim/obsidian.nvim#240]
### 🐛 Describe the bug

Pressing `Enter` with the cursor over an inline tag the tags picker does not open (a checkbox gets added instead).

But entering the command `:ObsidianTags #obsidian` works.

This appears to be a regression, reverting to v3.12.0 from the current HEAD (513e391) resolves the problem.

### Config

```lua
 return {
  "obsidian-nvim/obsidian.nvim", -- A community fork of epwalsh/obsidian.nvim
  version = "*",                 -- Use latest release instead of latest commit
  lazy = true,
  ft = "markdown",
  dependencies = {
    "nvim-lua/plenary.nvim",
    'nvim-telescope/telescope.nvim',
  },
  config = function()
    local obsidian = require 'obsidian'
    obsidian.setup {
      workspaces = {
        {
          -- PKM notes
          name = "notes",
          path = "~/share/notes",
        },
        {
          -- Legacy and non-PKM-related documents
          name = "doc",
          path = "~/share/doc",
        },
      },
      attachments = {
        img_folder = "attachments",
        img_name_func = function()
          return "" -- No default file name
        end,
        -- FIX: Leave path separators in encoded paths (see https://github.com/obsidian-nvim/obsidian.nvim/issues/119)
        img_text_func = function(client, path)
          path = client:vault_relative_path(path) or path
          local caption = vim.fs.basename(tostring(path))
          caption = caption:match("^(.*)%.([^%.]*)$") or caption -- Strip file name extension
          local encoded_path = vim.uri_from_fname(tostring(path))
          encoded_path = encoded_path:match("^file://(.*)")      -- Strip leading 'file://'
          return string.format("![%s](%s)", caption, encoded_path)
        end,
      },
      templates = {
        folder = "templates",
        date_format = "%Y-%m-%d-%a",
        time_format = "%H:%M",
      },
      completion = {
        blink = true,  -- Enables completion using blink.cmp
        min_chars = 0, -- Completion trigger length
      },
      daily_notes = {
        folder = "daily",
        workdays_only = false,
      },
      note_id_func = function(title)
        local current_dir = vim.fn.getcwd() -- Assume the new note will reside in Neovim's current working directory
        local id = Utils.slugify(title or "untitled", current_dir, ".md")
        return id
      end,
      picker = {
        -- Set preferred picker. Can be one of 'telescope.nvim' (default), 'fzf-lua', 'mini.pick' or 'snacks.pick'.
        name = "telescope.nvim",
      },
    }
    vim.keymap.set('n', '<Leader>os', "<Cmd>ObsidianTOC<CR>", { desc = "Markdown section headers picker" })
    vim.keymap.set('n', '<Leader>od', "<Cmd>ObsidianToday<CR>", { desc = "New daily note for today" })
    vim.keymap.set('n', '<Leader>oi', "<Cmd>ObsidianPasteImg<CR>", { desc = "Insert image from clipboard" })
    vim.keymap.set('n', '<Leader>on', "<Cmd>ObsidianNew<CR>", { desc = "New note" })
    vim.keymap.set('n', '<Leader>oN', "<Cmd>ObsidianTemplate<CR>", { desc = "New note from template" })
    vim.keymap.set('n', '<Leader>oo', "<Cmd>ObsidianOpen<CR>", { desc = "Open note in Obsidian application" })
    vim.keymap.set('n', '<Leader>of', "<Cmd>ObsidianQuickSwitch<CR>", { desc = "Notes file picker" })
    vim.keymap.set('n', '<Leader>og', "<Cmd>ObsidianSearch<CR>", { desc = "Search notes files with ripgrep" })
    vim.keymap.set('n', '<Leader>ot', "<Cmd>ObsidianTags<CR>", { desc = "Search for tagged notes" })
    -- Links related commands
    vim.keymap.set('n', '<Leader>ll', "<Cmd>ObsidianLinks<CR>", { desc = "Links picker" })
    vim.keymap.set('n', '<Leader>lb', "<Cmd>ObsidianBacklinks<CR>", { desc = "Backlinks picker" })
    vim.keymap.set('v', '<Leader>le', ":ObsidianLink<CR>",
      { desc = "Replace selected note ID, path or alias with a link to an existing note" })
    vim.keymap.set('v', '<Leader>ln', ":ObsidianLinkNew<CR>",
      { desc = "Replace selected note title of with a link to a new note" })
  end,
}
```

### Environment

```

==============================================================================
obsidian:                                                                   ✅

- ✅ OK neovim >= 0.11

obsidian.nvim [Version] ~
- ✅ OK Obsidian.nvim v3.12.0 (2f0222b3eb20382cadf3e1d91f368318b768771c)

obsidian.nvim [Pickers] ~
- ✅ OK ✓ telescope.nvim: a0bbec21143c7bc5f8bb02e0005fa0b982edc026

obsidian.nvim [Completion] ~
- ✅ OK ✓ blink.cmp: 9bcb14b43852a6f2bfd5ac9ef29cb5cf09b1b39b

obsidian.nvim [Dependencies] ~
- ✅ OK ✓ rg: ripgrep 14.1.1
- ✅ OK ✓ plenary.nvim: 857c5ac632080dba10aae49dba902ce3abf91b35
```

**Comment by sotte** [comment]
I can confirm that something is off with the `smart action` (or at least it manifests in the `smart action`). I actually thought that obsidian.nvim is completely broken as the smart action is the main way I interact with obsidian.

With the `smart action` I CANNOT

- toggle checkboxes (`ObsidianToggleCheckbox` works though)
- follow links (neither web links nor internal links)
- show tags when on a `#tag`
- fold headings

I tested it with version 513e391.
I also checked out an older version de20039 (just a random version that I used in the past) and it works.

**Comment by neo451** [comment]
I see, will resolve this as soon as possible.

**Comment by neo451** [comment]
> With the `smart action` I CANNOT

Really weird, smart_action is entirely broken for some folks, but not others.

Inline tags is broken because the pattern matching is wrong after #206 because wanting to avoid tag false positives. I think I can revert it for now so that it works again. @srackham 

@sotte maybe you can show me your current config?

**Comment by sotte** [comment]
@neo451, here are the details you asked for. 
I did not have time to look into why this problem exists 🙈 

## Versions

obsidian commit: 7d869a2

```
nvim --version
NVIM v0.11.2
Build type: Release
LuaJIT 2.1.1741730670
```

## `:checkhealth obsidian`

```example
==============================================================================
obsidian:                                                                   ✅

- ✅ OK neovim >= 0.11

obsidian.nvim [Version] ~
- ✅ OK Obsidian.nvim v3.12.0 (7d869a2477563b815bea4877e641d241c28b912f)

obsidian.nvim [Environment] ~
- ✅ OK • operating system: Linux

obsidian.nvim [Config] ~
- ✅ OK • dir: /home/stefan/org

obsidian.nvim [Pickers] ~
- ✅ OK ✓ snacks.nvim: bc0630e43be5699bb94dadc302c0d21615421d93

obsidian.nvim [Completion] ~
- ✅ OK ✓ blink.cmp: 9bcb14b43852a6f2bfd5ac9ef29cb5cf09b1b39b

obsidian.nvim [Dependencies] ~
- ✅ OK ✓ rg: 14.1.1
- ✅ OK ✓ plenary.nvim: 857c5ac632080dba10aae49dba902ce3abf91b35
```

## The config:
```
return {
  {
    -- "obsidian-nvim/obsidian.nvim",
    dir = "/home/stefan/coding/obsidian.nvim/",
    dependencies = {
      "MeanderingProgrammer/render-markdown.nvim",
    },
    ft = "markdown",

    keys = {
      -- ...
    },

    opts = {
      ui = { enable = false },
      workspaces = {
        { name = "org", path = "~/org/" },
        { name = "obsdev", path = "~/obsdev/" },
      },

      new_notes_location = "notes_subdir",
      note_id_func = function(title)
        -- Create note IDs in a Zettelkasten format with a timestamp and a suffix.
        -- In this case a note with the title 'My new note' will be given an ID that looks
        -- like '1657296016-my-new-note', and therefore the file name '1657296016-my-new-note.md'
        local suffix = ""
        if title ~= nil then
          -- If title is given, transform it into valid file name.
          suffix = title:gsub(" ", "-"):gsub("[^A-Za-z0-9-]", ""):lower()
        else
          -- If title is nil, just add 4 random uppercase letters to the suffix.
          for _ = 1, 4 do
            suffix = suffix .. string.char(math.random(65, 90))
          end
        end
        -- YYYYMMDD
        return os.date("%Y%m%d") .. "-" .. suffix
        -- return tostring(os.time()) .. "-" .. suffix
      end,

      follow_img_func = function(img)
        vim.fn.jobstart({ "xdg-open", img })
      end,

      picker = { name = "telescope.nvim" },

      completion = {
        nvim_cmp = false,
        blink = true,
        min_chars = 2,
      },

      attachments = { confirm_img_paste = false },

      daily_notes = {
        folder = "journal",
        date_format = "%Y-%m-%d",
        alias_format = "%Y-%m-%d",
        template = "journal_entry.md",
      },
      templates = {
        -- ..
      },
    },
  },
}

```

**Comment by neo451** [comment]
@sotte should be resolved by https://github.com/obsidian-nvim/obsidian.nvim/commit/cc80395d6a710df0aa0faf5d7def46aa0f893e31

I accidentally set noremap for it. I think it should be resolved.

**Comment by neo451** [comment]
@srackham I reverted most of the changes in #206, so that it can work for now, because lua string patterns are not expressive enough for all the needs.

#225 takes an entirely different approach, just using `rg`'s regex to match, which should cover all cases

**Comment by sotte** [comment]
As always, thanks @neo451.
I just pulled cc80395 and did a quick check...

`<CR>` still does not trigger the smart action.

Actually I still don't have a mapping for `<CR>`. ~~I don't think the autocommand is triggered.~~ The autocommand is triggered.

I manually called `:lua require("obsidian.builtin").smart_action()` when I was on heading, tags, etc. The function is executed and the correct parts (heading, tags, etc) are recognized, but no action is taken. No idea why.

----

Some more investigation. The recent changes regarding the path handing caused a bit confusion.
My notes are in `~/org` which symlinks to another place.
With the new path logic, the workspace check fails (and a bunch of commands are not executed, among other things registering of the smart actions):

![Image](https://github.com/user-attachments/assets/a92d251a-506a-4a29-a038-fcc92e672f32)

**Comment by sotte** [comment]
Changing my workspace dir to symlinkd folder helps. Now the smart action is registered and I can use <CR>.

~~But no action is executed. Checking...~~ My bad, I broke something while debugging. The action is executed now.

I wonder if we should improve the current situation with symlinks and at least warn the user. `ObsidianDebug` would be good for this...well, this command does not exist anymore :)

**Comment by sotte** [comment]
@srackham can you confirm that you don't have this problem anymore. The we can close this issue.

**Comment by neo451** [comment]
@sotte thank you for pointing out the real issue. Will look into the symlink issue.

I removed `Obsidian debug` since it is overlapping with healthcheck, and `Obsidian check`.

**Comment by neo451** [comment]
@sotte I think the new commit should resolve the symlink issue.

**Comment by srackham** [comment]
@sotte @neo451 The Smart Action over tags seems to be fixed.
