### ISSUE TITLE
passthrough function no longer creates a note from a link

### ISSUE THREAD

**Issue by ReedMerrill** [obsidian-nvim/obsidian.nvim#332]
### 🐛 Describe the bug

Before updating yesterday, I was able to surround some text in double square brackets, and then, with my cursor over the surrounded text (which was a link to a file that didn't exist), use the `gf` keymap to create the file and then go to it. Now I get an this error: `E447: Can't find file "about" in path`

## reprex:

Given some text:

```markdown
- [ ] ask about new RAs
```

1. Create a new link to a note that doesn't exist

```markdown
- [ ] [[ask about new RAs]]
```

2. In normal mode, use the `gf` keymap while the cursor is over the new link

```markdown
- [ ] [[ask about new RAs]]
       <!--  ^cursor here -->
```

3. Get the error: `E447: Can't find file "about" in path`

I added

```lua
completion = {
  create_new = true,
}
```

but the feature still isn't working.

### Config

```lua
{
  "obsidian-nvim/obsidian.nvim",
  version = "*", -- recommended, use latest release instead of latest commit
  ui = {
    enable = true,
    checkboxes = {
      [" "] = { char = "󰄱", hl_group = "ObsidianTodo" },
      ["x"] = { char = "", hl_group = "ObsidianDone" },
      [">"] = { char = "", hl_group = "ObsidianRightArrow" },
      ["~"] = { char = "󰰱", hl_group = "ObsidianTilde" },
      ["!"] = { char = "", hl_group = "ObsidianImportant" },
      -- [" "] = { char = "☐", hl_group = "ObsidianTodo" },
      -- ["x"] = { char = "✔", hl_group = "ObsidianDone" },
    },
  },
  lazy = true,
  -- for activating on all markdown files
  ft = "markdown",
  dependencies = {
    -- Required.
    "nvim-lua/plenary.nvim",
  },
  opts = {
    workspaces = {
      {
        name = "CMB",
        path = cmb,
      },
      {
        name = "main",
        path = main,
      },
    },
    -- customize how note IDs are generated given an optional title.
    ---@param title string|?
    ---@return string
    note_id_func = function(title)
      if title ~= nil then
        -- Transform title into a valid file name.
        title = title:gsub(" ", "-"):gsub("[^A-Za-z0-9-]", ""):lower()
      else
        -- If title is nil, return an error.
        error("No file name argument provided.")
      end
      return title
    end,
    completion = {
      create_new = true,
      -- Set to false to disable completion.
      nvim_cmp = true,
      -- Trigger completion at 2 chars.
      min_chars = 2,
    },
  },
}
```

### Environment

```

==============================================================================
obsidian:                                   require("obsidian.health").check()

- ✅ OK neovim >= 0.11

obsidian.nvim [Version] ~
- ✅ OK obsidian.nvim v3.13.0 (5186cba27b256daae5f824b2789e016161f0b20c)

obsidian.nvim [Environment] ~
- ✅ OK operating system: Darwin

obsidian.nvim [Config] ~
- ✅ OK • dir: /Users/reed/Can. Mun. Barometer Dropbox/Reed Merrill/3-resources/obsidian/CMB

obsidian.nvim [Pickers] ~
- ✅ OK telescope.nvim: a0bbec21143c7bc5f8bb02e0005fa0b982edc026
- ✅ OK snacks.nvim: bc0630e43be5699bb94dadc302c0d21615421d93

obsidian.nvim [Completion] ~
- ✅ OK nvim-cmp: b5311ab3ed9c846b585c0c15b7559be131ec4be9

obsidian.nvim [Dependencies] ~
- ✅ OK rg: 14.1.1
- ✅ OK pngpaste: found

```

**Comment by neo451** [comment]
ah yes, I know why this is, this bug is introduce because I refactored the follow_link functions, will fix this ASAP.

**Comment by neo451** [comment]
@ReedMerrill should be fixed now

**Comment by jasonminsookim** [comment]
Can we cut a release with this new fix? I downgraded to v3.11.0 in the meantime to not encounter this bug.

**Comment by ReedMerrill** [comment]
Yup, thanks! it works with the smart action now, but still not `gf`

**Comment by neo451** [comment]
@ReedMerrill I intentionally removed default mapping from `gf` to `Obsidian follow_link`, for one it is a bit random, if gf why not override gx as well, and why stuff like `gF` and related won't work. for another, there should be a more general and LSP driven follow_link rework, so we can just map yourself for now. Follow: https://github.com/obsidian-nvim/obsidian.nvim/wiki/Keymaps

**Comment by neo451** [comment]
> Can we cut a release with this new fix? I downgraded to v3.11.0 in the meantime to not encounter this bug.

will do :)

**Comment by neo451** [comment]
this is released in v3.13.1 @jasonminsookim try it?

**Comment by jasonminsookim** [comment]
@neo451  Works for me! Thanks, feels a bit slower performance wise than before, but works nonetheless
