### ISSUE TITLE
[LSP] After update, errors out if `nvim-navic` is enabled

### ISSUE THREAD

**Issue by ahmedelgabri** [obsidian-nvim/obsidian.nvim#455]
### 🐛 Describe the bug

I get these errors when I open a Markdown file, this only happens if `https://github.com/SmiteshP/nvim-navic` is enabled. 

```
Error detected while processing BufEnter Autocommands for "*.md"..LspAttach Autocommands for "*":
Error executing lua callback: ...idian.nvim/lua/obsidian/lsp/handlers/document_symbol.lua:5: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...idian.nvim/lua/obsidian/lsp/handlers/document_symbol.lua:5: in function <...idian.nvim/lua/obsidian/lsp/handlers/document_symbol.lua:4>
        .../share/nvim/lazy/obsidian.nvim/lua/obsidian/lsp/init.lua:18: in function 'request'
        ...wrapped-0.11.4/share/nvim/runtime/lua/vim/lsp/client.lua:681: in function 'request'
        ....local/share/nvim/lazy/nvim-navic/lua/nvim-navic/lib.lua:270: in function 'request'
        ....local/share/nvim/lazy/nvim-navic/lua/nvim-navic/lib.lua:275: in function 'request_symbol'
        ...local/share/nvim/lazy/nvim-navic/lua/nvim-navic/init.lua:398: in function <...local/share/nvim/lazy/nvim-navic/lua/nvim-navic/init.lua:325>
        [C]: in function 'nvim_exec_autocmds'
        ...wrapped-0.11.4/share/nvim/runtime/lua/vim/lsp/client.lua:1025: in function 'on_attach'
        ...ovim-unwrapped-0.11.4/share/nvim/runtime/lua/vim/lsp.lua:1044: in function 'buf_attach_client'
        ...ovim-unwrapped-0.11.4/share/nvim/runtime/lua/vim/lsp.lua:751: in function <...ovim-unwrapped-0.11.4/share/nvim/runtime/lua/vim/lsp.lua:703>
        [C]: in function 'pcall'
        .../share/nvim/lazy/obsidian.nvim/lua/obsidian/lsp/init.lua:31: in function 'start'
        .../share/nvim/lazy/obsidian.nvim/lua/obsidian/autocmds.lua:65: in function <.../share/nvim/lazy/obsidian.nvim/lua/obsidian/autocmds.lua:26>
Press ENTER or type command to continue
```

```
Error detected while processing CursorHold Autocommands for "<buffer=1>":
Error executing lua callback: ...idian.nvim/lua/obsidian/lsp/handlers/document_symbol.lua:5: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...idian.nvim/lua/obsidian/lsp/handlers/document_symbol.lua:5: in function <...idian.nvim/lua/obsidian/lsp/handlers/document_symbol.lua:4>
        .../share/nvim/lazy/obsidian.nvim/lua/obsidian/lsp/init.lua:18: in function 'request'
        ...wrapped-0.11.4/share/nvim/runtime/lua/vim/lsp/client.lua:681: in function 'request'
        ....local/share/nvim/lazy/nvim-navic/lua/nvim-navic/lib.lua:270: in function 'request'
        ....local/share/nvim/lazy/nvim-navic/lua/nvim-navic/lib.lua:275: in function 'request_symbol'
        ...local/share/nvim/lazy/nvim-navic/lua/nvim-navic/init.lua:364: in function <...local/share/nvim/lazy/nvim-navic/lua/nvim-navic/init.lua:360>
Press ENTER or type command to continue
```

### Config

```lua
{
	'https://github.com/obsidian-nvim/obsidian.nvim',
	version = '*',
	cmd = { 'Obsidian' },
	ft = { 'markdown' },
	dependencies = {
		'https://github.com/nvim-lua/plenary.nvim',
	},
	opts = {
		legacy_commands = false,
		workspaces = {
			{
				name = 'notes',
				path = vim.env.NOTES_DIR,
				strict = true,
				overrides = {
					attachments = {
						img_folder = vim.env.NOTES_DIR .. '/assets',
						img_name_func = function()
							return string.format(
								'%s/%s/Pasted image %s',
								vim.env.NOTES_DIR .. '/assets',
								vim.fn.expand '%:t:r',
								os.date '%Y%m%d%H%M%S'
							)
						end,
					},
				},
			},
			{
				name = 'no-vault',
				path = function()
					-- alternatively use the CWD:
					-- return assert(vim.fn.getcwd())
					return vim.fs.dirname(vim.api.nvim_buf_get_name(0))
				end,
				overrides = {
					frontmatter = {
						enable = false,
					},
					notes_subdir = vim.NIL, -- have to use 'vim.NIL' instead of 'nil'
					new_notes_location = 'current_dir',
					templates = {
						folder = vim.NIL,
					},
					attachments = {
						img_folder = 'assets',
					},
					daily_notes = {
						folder = vim.NIL,
					},
				},
			},
		},

		templates = {
			folder = '.zk/templates', -- must be relative to the root of the vault
			date_format = '%Y-%m-%d',
			time_format = '%H:%M',
			-- A map for custom variables, the key should be the variable and the value a function
			substitutions = {
				-- zk compatibility
				-- https://zk-org.github.io/zk/notes/template.html#date-formatting-helper
				['format-date now "%Y-%m-%dT%H:%M"'] = function()
					return os.date '%Y-%m-%dT%H:%M' -- 2025-04-01T12:05
				end,
				['format-date now "timestamp"'] = function()
					return os.date '%Y%m%d%H%M' -- 202504011205
				end,
				["format-date now '%Y-%m-%d'"] = function()
					return os.date '%Y-%m-%d' -- 2025-04-01
				end,
				['format-date now "long"'] = function()
					return os.date '%B %d, %Y' -- April 1, 2025
				end,
				['content'] = function()
					return ''
				end,
				['extra.employer'] = function()
					return vim.env.COMPANY or 'NO COMPANY'
				end,
			},
		},

		---@param title string|?
		---@return string
		note_id_func = function(title)
			local note_name = tostring(os.date '%Y%m%d%H%M')

			if title ~= nil then
				note_name = note_name
					.. ' '
					.. title:gsub(' ', '-'):gsub('[^A-Za-z0-9-]', ''):lower()
			end

			return note_name
		end,

		frontmatter = {
			-- Optional, alternatively you can customize the frontmatter data.
			---@return table
			func = function(note)
				local function convert_date(date_string)
					local year, month, day, hour, min

					-- Try to match date with time
					year, month, day, hour, min =
						date_string:match '(%d+)-(%d+)-(%d+)[T ](%d+):(%d+)'

					if not year then
						-- Try to match date only
						year, month, day = date_string:match '(%d+)-(%d+)-(%d+)'
						hour, min = 0, 0
					end

					if year then
						-- Create date table for os.time
						local date_table = {
							year = tonumber(year),
							month = tonumber(month),
							day = tonumber(day),
							hour = tonumber(hour) or 0,
							min = tonumber(min) or 0,
							sec = 0,
						}

						-- Convert to timestamp
						local timestamp = os.time(date_table)

						-- Format using os.date
						return os.date('%Y%m%d%H%M', timestamp)
					else
						return nil, 'Invalid date format'
					end
				end

				-- Add the title of the note as an alias.
				if note.title then
					note:add_alias(note.title)
				end

				local out = {
					aliases = note.aliases,
					tags = note.tags,
				}

				-- `note.metadata` contains any manually added fields in the frontmatter.
				-- So here we just make sure those fields are kept in the frontmatter.
				if note.metadata ~= nil and not vim.tbl_isempty(note.metadata) then
					for k, v in pairs(note.metadata) do
						out[k] = v
					end
				end

				-- We run this at the end so we have access to metadata too
				out.id = note.id
					or tostring(convert_date(note.metadata.date))
					or tostring(os.date '%Y%m%d%H%M')

				return out
			end,
		},

		daily_notes = {
			folder = 'journal',
			workdays_only = false,
			default_tags = { 'journal' },
			template = 'journal.md',
		},

		completion = {
			nvim_cmp = false,
			blink = false,
		},

		ui = {
			enable = false,
		},

		attachments = {
			img_folder = 'assets',
		},
		footer = {
			enabled = false,
		},
	},
},
```

### Environment

```

==============================================================================
obsidian:                                                                   ✅

- ✅ OK neovim >= 0.11

obsidian.nvim [Version] ~
- ✅ OK obsidian.nvim v3.14.1 (a1d2617a5d1db4b8c53a3431943168e7a28a38d7)

obsidian.nvim [Environment] ~
- ✅ OK operating system: Darwin

obsidian.nvim [Config] ~
- ✅ OK • dir: /Users/ahmedelgabri/Sync/notes

obsidian.nvim [Pickers] ~
- ✅ OK fzf-lua: c0c0926eee09f2e7868e5b72cb66decc0cb13aca
- ✅ OK mini.nvim: fbb6ad02871d296fc7d3ebd453e1be89b1210f68
- ✅ OK snacks.nvim: bfe8c26dbd83f7c4fbc222787552e29b4eccfcc0

obsidian.nvim [Completion] ~
- ✅ OK blink.cmp: 327fff91fe6af358e990be7be1ec8b78037d2138

obsidian.nvim [Dependencies] ~
- ✅ OK rg: 14.1.1
- ✅ OK pngpaste: found

```

**Comment by neo451** [comment]
pin back to `3.13.*` to solve the issue.

> vim.lsp.enable('obsidian-ls', false)

I guess this could be an reoccurring question so I take this chance to explain.

`vim.lsp.config` and `vim.lsp.enable` is a great tool to manage, when to spawn LSP server, the external program running elsewhere, as resource management it makes sense.

But here we have an "in-process LSP", the server is just a lookup table in memory of handler functions, and gradually most of the functions that this plugin supports will be in form of these handlers, so it does not make much sense to `disable` or control when to enable this LSP through `vim.lsp.enable` and `vim.lsp.config`.

When it activates is whenever we are in a markdown file that is in the configured workspace.

So in this specific case and #452, is all because another internal API function is now buggy, once we fix them, the LSP should work fine and does not conflict with LSP related plugins like nvim-navic, instead the point of LSP transformations is that we get these plugin's integration for free.

**Comment by neo451** [comment]
I pushed an attempted fix, remove pin to get on main to see if the error goes away. @ahmedelgabri

**Comment by ahmedelgabri** [comment]
@neo451 thanks, maybe I was not very clear about `vim.lsp.enable('obsidian-ls', false)` I added this inside `init = function() ... end` but maybe that's still too late. 

> I pushed an attempted fix, remove pin to get on main to see if the error goes away. @ahmedelgabri 

I still get this error

```
Error detected while processing CursorHold Autocommands for "<buffer=2>":
Error executing lua callback: ...idian.nvim/lua/obsidian/lsp/handlers/document_symbol.lua:5: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...idian.nvim/lua/obsidian/lsp/handlers/document_symbol.lua:5: in function <...idian.nvim/lua/obsidian/lsp/handlers/document_symbol.lua:4>
        .../share/nvim/lazy/obsidian.nvim/lua/obsidian/lsp/init.lua:18: in function 'request'
        ...wrapped-0.11.4/share/nvim/runtime/lua/vim/lsp/client.lua:681: in function 'request'
        ....local/share/nvim/lazy/nvim-navic/lua/nvim-navic/lib.lua:270: in function 'request'
        ....local/share/nvim/lazy/nvim-navic/lua/nvim-navic/lib.lua:275: in function 'request_symbol'
        ...local/share/nvim/lazy/nvim-navic/lua/nvim-navic/init.lua:364: in function <...local/share/nvim/lazy/nvim-navic/lua/nvim-navic/init.lua:360>
Press ENTER or type command to continue
```

**Comment by neo451** [comment]
sure you did update? then that is even more weird.

**Comment by neo451** [comment]
I relaxed the condition further, should produce no errors now, but can you check if the document symbol related functionality in nvim-navic works?

**Comment by ahmedelgabri** [comment]
@neo451 now it's working fine. No errors, thank you.
