### ISSUE TITLE
obsidian template fail

### ISSUE THREAD

**Issue by Shawn-Summer** [obsidian-nvim/obsidian.nvim#580]
### 🐛 Describe the bug

when i type `obsidian template ` or `obsidian new_from_template`, something become wrong ( However, obsidian search and  quick_switch goes well ):

```
Snacks          Command failed: - cmd: `rg --files --no-messages --color never -g !.git --no-config --type-add md:*.qmd --type=md --files --sortr=modified --ignore-case --glob-case-insensitive`
```

### Config

```
return {
  "obsidian-nvim/obsidian.nvim",
  version = "*",
  ft = "markdown",
  opts = {
    legacy_commands = false,
    workspaces = {
      {
        name = "personal",
        path = "~/MyNotes/MyNotes",
      },
    },
    templates = {
      folder = "templates",
      date_format = "%Y-%m-%d-%a",
      time_format = "%H:%M",
    },
  },
}
 ```

```
❯ pwd
/Users/xxl/MyNotes/MyNotes/templates
❯ tree .
.
├── Daily.md
└── default.md

```

### Environment

```

==============================================================================
obsidian:                                                                   ✅

- ✅ OK neovim >= 0.11 (0.11.5)

obsidian.nvim [Version] ~
- ✅ OK obsidian.nvim v3.14.8 (de60246baec087aaf5bbf95e3f976e0897548d89)

obsidian.nvim [Environment] ~
- ✅ OK operating system: Darwin

obsidian.nvim [Config] ~
- ✅ OK • dir: /Users/xxl/MyNotes/MyNotes

obsidian.nvim [Pickers] ~
- ✅ OK snacks.nvim: a4e46becca45eb65c73a388634b1ce8aad629ae0

obsidian.nvim [Completion] ~
- ✅ OK nvim-cmp: d97d85e01339f01b842e6ec1502f639b080cb0fc

obsidian.nvim [Dependencies] ~
- ✅ OK rg: 15.1.0
- ✅ OK pngpaste: found

```

##  may help

i seem to get the reason:

when i use this command in the terminal, it goes well
```
rg --files --no-messages --color never -g '!.git' --no-config --type-add 'md:*.qmd' --type=md --files --sortr=modified --ignore-case --glob-case-insensitive
```

but if the `!.git` or `md:*.qmd` don't quoted by `‘` , it fails

```
zsh: no matches found: !.git
```

**Comment by neo451** [comment]
I pushed a small test change which confirms through CI that the arguments this plugin builds runs correctly on all platforms

but I really don't believe it is a shell escaping issue, since pickers should be using `libuv` under the hood, and no shell should be involved. (but I also see snacks seem to use a more custom version directly calling libuv functions instead of `vim.system`.

would you just install any other picker, no need to setup it up, just have them locally, and set picker option to other three `mini.pick` `telescope` or `fzf-lua`, to see if the error still exists?

**Comment by Shawn-Summer** [comment]
> I pushed a small test change which confirms through CI that the arguments this plugin builds runs correctly on all platforms
> 
> but I really don't believe it is a shell escaping issue, since pickers should be using `libuv` under the hood, and no shell should be involved. (but I also see snacks seem to use a more custom version directly calling libuv functions instead of `vim.system`.
> 
> would you just install any other picker, no need to setup it up, just have them locally, and set picker option to other three `mini.pick` `telescope` or `fzf-lua`, to see if the error still exists?

set picker option to other three mini.pick telescope or fzf-lua. I've already tried, the error still exists. They dont throw any error, but return a empty results, that is , cant show any files under the template folder.

And  I  reinstall the neovim and the lazyvim ,which install the default snacks.picker and obsidian.nvim , also i reinstall  greprip, unfortunately, the error still exists:

```
 07:48           Snacks          Command failed: - cmd: `rg --files --no-messages --color never -g !.git --no-config --type-add md:*.qmd --type=md --files --sortr=modified --ignore-case --glob-case-insensitive`
```

**Comment by Shawn-Summer** [comment]
I have solved it. The culprit is I add templates folder to .gitignore  that causes the error for calling the picker since the picker default ignore the files within the .gitignore. Anyway, thanks

**Comment by ErickKramer** [comment]
I am experiencing a similar behavior, but when adding a callout

```console
Command '{ "rg", "--no-config", "--type-add", "md:.qmd", "--type=md",
"--files", "--sortr=modified", "--ignore-case", "-g!Templates", "-g", "!WARNING*.md",
"--glob-case-insensitive", "/home/ekramer/Notes" }' exited with non-zero code 2. See logs for stderr.
```

I tried to find something in the issues, but this was the closest match to my problem

**Comment by neo451** [comment]
@ErickKramer the error will be gone on the main and released soon

but link completion will still be triggered, which will be fixed by #507 later

**Comment by ErickKramer** [comment]
> [@ErickKramer](https://github.com/ErickKramer) the error will be gone on the main and released soon
> 
> but link completion will still be triggered, which will be fixed by [#507](https://github.com/obsidian-nvim/obsidian.nvim/pull/507) later

Sweet! Thanks a lot! 😄

**Comment by StalwartS0ul** [comment]
> [@ErickKramer](https://github.com/ErickKramer) the error will be gone on the main and released soon
> 
> but link completion will still be triggered, which will be fixed by [#507](https://github.com/obsidian-nvim/obsidian.nvim/pull/507) later

Great to hear. Encountered this issue today when I needed to edit a callout.
